### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by linzexin022**
Corrected Chinese localization

### CODE REVIEW

**Comment by noriokun4649** [comment]
The master branch is the Minecraft 1.7.10 version and is not currently maintained.
The currently active branch is 1.19.

**Comment by noriokun4649** [comment]
No response, so I'm closing.

**Comment by linzexin022** [comment]
oops, sorry that I just saw it.

**Comment by linzexin022** [comment]
I've checked the branches of latest versions, the translations have all been corrected, but the translations of the latest versions (1.18.x and 1.19.x) mod on Fabric Loader I‘ve downloaded have not been corrected.

**Comment by noriokun4649** [comment]
> but the translations of the latest versions (1.18.x and 1.19.x) mod on Fabric Loader I‘ve downloaded have not been corrected.

Wow, I did not notice that.
I will correct it.

**Pull request closed without merging**
